projects:
  airbnb:
    schemaPath: >-
      Users/victorkabagema/Documents/GitHub/react-native-clones/Airbnb/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: >-
          /Users/victorkabagema/Documents/GitHub/react-native-clones/Airbnb/graphql
